### PR TITLE
BAU-198 Add release notes for 2.8.0

### PR DESCRIPTION
**Pull request by horakihor**

### CODE REVIEW

**Comment by horakihor** [comment]
Hi @JakeSCahill , it's the first time I make changes in this system, please let me know if I do everything correctly. Thanks

**Review by uddr — APPROVED** [review]

**Comment by JakeSCahill** [comment]
> Hi @JakeSCahill , it's the first time I make changes in this system, please let me know if I do everything correctly. Thanks

Everything looks good 👍  The link checker is just picking up some links that should be ignored anyway.

**Review by JakeSCahill — APPROVED** [review]
It would be nice to have more details about the fixes or any available links to the issues or PRs where they were fixed

**Comment by huseyinbabal** [comment]
> It would be nice to have more details about the fixes

Drawbacks about release note items in cloud is, project is not public, normally in other companies, they just refer to an issue, but currently we cannot do that since all the issues are private. However, I agree we can add more details

**Pull request merged**
